import jsPDF from "jspdf";
import type { ScanResult } from "./mock-data";

/**
 * Generates a clean, printer-friendly PDF report for a Hawkeye security scan result.
 * Downloads the PDF directly in the user's browser.
 *
 * @param scan - The ScanResult object to generate a report for
 */
export async function exportScanReportPDF(scan: ScanResult): Promise<void> {
  // Small artificial delay so loading spinner is perceptible to user
  await new Promise((resolve) => setTimeout(resolve, 300));

  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 20;

  // ── Header: Hawkeye Wordmark ──
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(27, 35, 64); // #1B2340 dusk
  doc.text("HAWKEYE", 20, y);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(142, 150, 174); // #8E96AE feather
  doc.text("WEB SECURITY ASSESSMENT REPORT", pageWidth - 20, y, { align: "right" });

  y += 6;
  doc.setDrawColor(227, 155, 60); // #E39B3C talon accent
  doc.setLineWidth(0.8);
  doc.line(20, y, pageWidth - 20, y);

  y += 12;

  // ── Target Overview Block ──
  doc.setFillColor(245, 247, 250);
  doc.roundedRect(20, y, pageWidth - 40, 28, 2, 2, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(27, 35, 64);
  doc.text(scan.url, 26, y + 10);

  doc.setFont("courier", "normal");
  doc.setFontSize(9);
  doc.setTextColor(100, 110, 130);
  doc.text(`Scan ID: ${scan.id}   |   Date: ${new Date(scan.scannedAt).toUTCString()}`, 26, y + 18);

  // Score badge in header block
  const scoreBoxX = pageWidth - 55;
  doc.setFillColor(scan.score >= 70 ? 82 : scan.score >= 40 ? 227 : 225, scan.score >= 70 ? 169 : scan.score >= 40 ? 155 : 79, scan.score >= 70 ? 127 : 60);
  doc.roundedRect(scoreBoxX, y + 6, 28, 16, 2, 2, "F");
  doc.setFont("courier", "bold");
  doc.setFontSize(14);
  doc.setTextColor(255, 255, 255);
  doc.text(`${scan.score}`, scoreBoxX + 14, y + 16, { align: "center" });

  y += 38;

  // ── Section: Category Breakdown ──
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(27, 35, 64);
  doc.text("SECURITY CATEGORIES BREAKDOWN", 20, y);

  y += 6;

  // Table Headers
  doc.setFillColor(230, 235, 245);
  doc.rect(20, y, pageWidth - 40, 8, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(60, 70, 90);
  doc.text("CATEGORY", 24, y + 5.5);
  doc.text("STATUS", 100, y + 5.5);
  doc.text("DETAILS", 130, y + 5.5);

  y += 8;

  // Category Rows
  scan.categories.forEach((cat, idx) => {
    // Alternating background
    if (idx % 2 === 1) {
      doc.setFillColor(250, 252, 255);
      doc.rect(20, y, pageWidth - 40, 18, "F");
    }

    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(30, 40, 60);
    doc.text(cat.name, 24, y + 8);

    // Status pill
    doc.setFont("courier", "bold");
    doc.setFontSize(9);
    if (cat.status === "pass") {
      doc.setTextColor(40, 140, 80);
    } else if (cat.status === "warning") {
      doc.setTextColor(190, 120, 20);
    } else {
      doc.setTextColor(200, 40, 40);
    }
    doc.text(cat.status.toUpperCase(), 100, y + 8);

    // Details text wrapping
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8.5);
    doc.setTextColor(80, 90, 110);
    const splitDetails = doc.splitTextToSize(cat.detail, pageWidth - 150);
    doc.text(splitDetails, 130, y + 6);

    y += 18;
    doc.setDrawColor(230, 235, 245);
    doc.setLineWidth(0.2);
    doc.line(20, y, pageWidth - 20, y);
  });

  // ── Footer ──
  const footerY = doc.internal.pageSize.getHeight() - 15;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(160, 170, 190);
  doc.text("Generated by Hawkeye Security Assessment • Confidential", pageWidth / 2, footerY, { align: "center" });

  // Filename formatting
  const hostname = scan.url.replace(/^https?:\/\//i, "").replace(/[^a-z0-9.-]/gi, "_");
  const dateStr = new Date(scan.scannedAt).toISOString().split("T")[0];
  const filename = `hawkeye-report-${hostname}-${dateStr}.pdf`;

  doc.save(filename);
}
